# Generated by Django 4.0.4 on 2022-05-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmodel',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolmodel',
            name='total_students',
            field=models.PositiveIntegerField(),
        ),
    ]
