# Generated by Django 4.0.4 on 2022-05-01 19:08
from faker import Faker
from django.db import migrations
from backend_api.utils import generate_unique

def generate_user(apps, schema_editor):
    fake = Faker()
    StudentModel = apps.get_model("backend_api", "StudentModel")
    SchoolModel = apps.get_model("backend_api", "SchoolModel")
    school = SchoolModel.objects.create(
        name=f"{fake.name()}'s", total_students=10)
    students = []
    for _ in range(5):
        students.append(StudentModel(
            first_name = fake.first_name(),
            last_name = fake.last_name(),
            address = fake.address(),
            school = school,
            id_string = generate_unique(20)

        ))
    StudentModel.objects.bulk_create(students)

class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_studentmodel_address_studentmodel_created_at'),
    ]

    operations = [
        migrations.RunPython(generate_user)
    ]
